 version: 2
 jobs:
   pylint:
     docker:
       - image: circleci/python:3.7.3
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 25
   test:
     docker:
       - image: circleci/python:3.7.3
     steps:
       - checkout
       - run: echo "A more familiar hi"
       - run: sleep 15
 workflows:
   version: 2
   pylint_and_test:
     jobs:
       - pylint
       - test
