 version: 2
 jobs:
   pylint:
     docker:
       - image: circleci/python:3.7.3
     steps:
       - checkout
       - run: echo "A first hello"
   test:
     docker:
       - image: circleci/python:3.7.3
     steps:
       - checkout
       - run: echo "A more familiar hi"
   deploy_docs:
     docker:
       - image: circleci/python:3.7.3
     steps:
       - checkout
       - run: echo "Building docs"

 workflows:
   version: 2
   pylint_and_test:
     jobs:
       - pylint
       - test
    deploy:
      jobs:
        - deploy_docs
