version: 2
jobs:
  pylint:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: echo "A first hello"
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: echo "A more familiar hi"
  deploy_docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run: make -C docs html
      - persist_to_workspace:
          root: docs/build
          paths: html

workflows:
  version: 2
  pylint_test_deploy:
    jobs:
      - pylint
      - test
      - deploy_docs:
          requires:
            - pylint
            - test
          filters:
            branches:
              only: master 
